project_id = "yuqemnbwndyjmpzxlwyv"

[functions.create-checkout]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false
