project_id = "yuqemnbwndyjmpzxlwyv"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false

[functions.geocode-restaurants]
verify_jwt = false

[functions.transfer-pending-payouts]
verify_jwt = false

[functions.create-connect-login-link]
verify_jwt = false
